default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.15
  hooks:
    - id: uv-lock
    - id: uv-sync
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
    - id: ruff-format
    - id: ruff
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.391
  hooks:
  - id: pyright
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 39.91.1
  hooks:
    - id: renovate-config-validator
