name: Python linting

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

jobs:
  python-linting:
    runs-on: ubuntu-latest
    name: "Python linting"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install uv
      uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5.1.0
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: |
        uv sync
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
    
    - name: Check file formatting
      uses: astral-sh/ruff-action@31a518504640beb4897d0b9f9e50a2a9196e75ba # v3.0.1
      with:
        args: "format --check"
        
    - name: Lint with ruff
      env:
        RUFF_OUTPUT_FORMAT: github
      run: |
        ruff check

    - name: Typecheck with pyright
      uses: jakebailey/pyright-action@b5d50e5cde6547546a5c4ac92e416a8c2c1a1dfe # v2.3.2
      with:
        version: PATH
  