name: Python linting

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

jobs:
  python-linting:
    runs-on: ubuntu-latest
    name: "Python linting"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python 3.13
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.13

    - name: Install uv
      uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a  # v5.1.0
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync
    
    - name: Check file formatting
      run: |
        uv run ruff format --check
        
    - name: Lint with ruff
      run: |
        uv run ruff check --output-format=github

    - name: Typecheck with pyright
      run: |
        uv run pyright
  